import Head from 'next/head'
import { Geist, Geist_Mono } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import { InferGetStaticPropsType } from 'next'
import ProductCard from '@/components/ProductCard'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin']
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin']
})

export const getStaticProps = async () => {
	const data = await fetch('https://dummyjson.com/products?limit=6')
		.then(res => res.json())
		.catch(err => console.error(err))

	return {
		props: {
			data
		}
	}
}

export default function Home({ data }: InferGetStaticPropsType<typeof getStaticProps>) {
	const { products } = data
	return (
		<>
			<Head>
				<title>My Store</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}>
				<section className={styles['title-section']}>
					<h1 className={styles.title}>Our Recommended Products</h1>
				</section>
				<section className={styles.main}>
					<div className={styles.grid}>
						{products &&
							products.map((product: Product) => <ProductCard key={product.sku} product={product} />)}
					</div>
				</section>
			</div>
		</>
	)
}
